### ISSUE TITLE
Ring of the Seven Curses Can be disassembled in Wireless Crafting Terminal

### ISSUE THREAD

**Issue by mustardwheat** [KELETU66666/EnigmaticLegacyLegacy#2]
I really like the needs ring function and I hope there is a way to fix it.
https://github.com/KELETU66666/EnigmaticLegacyLegacy/assets/88693726/8b8877b8-e7f5-4624-8417-93a75ecc47e1

Version：
enigmaticlegacy-0.0.4
WirelessCraftingTerminal-1.12.2-3.12.97

**Comment by KELETU66666** [comment]
fixed
