### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by pegek** [KELETU66666/EnigmaticLegacyLegacy#3]
Firstly, i want to thank you for your awesome work, i've been wondering if someone ever gonna make a port of this legendary mod to the best mc version, i appreciate your work.  If someone is using big amount of baubles-based mod im suggesting using small mod that will increase the number os avaliable ring slots https://www.curseforge.com/minecraft/mc-mods/bring-me-the-rings

**Comment by KELETU66666** [comment]
improved :), now cursed ring have a unique slot
