### ISSUE TITLE
與Bubbles有衝突

### ISSUE THREAD

**Issue by senfun** [KELETU66666/EnigmaticLegacyLegacy#4]
我正在使用Enigmatic Legacy²0.2.3和Bubbles2.0-2(原bubbles的一个fork) 他支持自订饰品插槽数量
但我使用这个bubbles之后无法开启Enigmatic Legacy²自带的饰品栏 可以请您修复这个问题吗 谢谢!

**Comment by KELETU66666** [comment]
下个版本将会有一个类似旅者之器的饰品栏，请稍等
