### ISSUE TITLE
[建议] 希望增加调整开启GUI位置的config

### ISSUE THREAD

**Issue by senfun** [KELETU66666/EnigmaticLegacyLegacy#5]
![image](https://github.com/user-attachments/assets/c5b914b9-f204-42b9-926a-eaeb0bb5e0b3)
如图 我正在组建一个大型整合包里面包含GalactiCraft，戴上七咒之戒后背包中开启末影箱GUI的图示会和GalactiCraft太空装的GUI图示重叠，希望增加一个可以调整GUI图示的config适配不同的整合包 再次感谢!

**Comment by KELETU66666** [comment]
已经有了，可以调整的，在config里
