### ISSUE TITLE
[request/suggestion] "conventional" slots

### ISSUE THREAD

**Issue by Biviho** [KELETU66666/EnigmaticLegacyLegacy#6]
hi! 
first of all, the items and effects looks really interesting! thanks for backporting the mod!

i have a request/suggestion if you would like it: would be possible to add an option to change the slot type of the items to the conventional baubles one (head, body, pendant, charm, ring, belt) and remove the additional ui? 
the best would be to make each item to have the slot customizable via config (for balancing)

the reason is:
there are some baubles fork that can increase the slots ([BaublesEx](https://www.curseforge.com/minecraft/mc-mods/baublesex) and [Bubbles](https://www.curseforge.com/minecraft/mc-mods/bubbles-a-baubles-fork/files/5719448)), so we are not limited to the normal baubles slots and a modpack dev can customize them for balancing in the pack. 
for the UI, the button tend to overlap with quark chest fill buttons and with nutrition button... and having both bauble ui and this ui can be confusing.

**Comment by KELETU66666** [comment]
i'll support https://www.curseforge.com/minecraft/mc-mods/bubbles-a-baubles-fork/files/5719448
