### ISSUE TITLE
[suggestion] add an option to not spawn with enigmatic pendant

### ISSUE THREAD

**Issue by Biviho** [KELETU66666/EnigmaticLegacyLegacy#7]
Hi! 
I wanted to ask if it was possible to add an option to remove the enigmatic pendant (if i remember the name correctly) from the player inventory on spawn

Aldo, i noticed that the enigmatic pendant does not appear in JEI, is it an item that is intended to transform intonsomething else? I read on a changelog about an enigmatic pendant with red gem, thats why i'm asking

The reason for removing the pendant is for modpack maker to add the items as crafting recipe or loot, it would be great to have this option c:

**Comment by KELETU66666** [comment]
got it :)
